PermissionDenied: Permission denied

SitePath: Site path
RegisterSite: Register a blog site
SiteRegistrationSucceed: Congratulations! You have successfully registered a new site. 
VisitHomepage: Click the following link to vist your site homepage: 
SiteRegistrationFailed: The site path has been registered by others. Please choose another path.
EnterPath: Enter your site path below. 
PathRegex: A path must begin with a lowercase letter and consists of lowercase letters, hyphens and digits.
FormMissing: Form data missing

Account: Account
UserNumber: User number
Number: No. 
Password: Password
ForgotPassword: Forgot password
SetPassword: Set a new password
EnterPasswordResetEmail: Enter your e-mail address below, and a password reset e-mail will be sent to you.
Login: Login
LoginViaEmail: Login via email
LoginViaGoogle: Login via Google
NewGoogle: Connect to a new google account
Email: Email
Site: Site
Profile: Profile
User: User
Name: Name
Avatar: Avatar
About: About
Subscription: Subscription
Notification: Notification
EmailNotification: Email notification
NotifyMeViaEmail: Notify me via email when I receive a comment or reply.
NewEmail: Add a new Email
Editor: Editor
DefaultPreamble: Default LaTeX Preamble
Preamble: LaTeX Preamble
DefaultCitation: Default Citation
Citation: Citation
Edit: Edit
View: View
Save: Save
Update: Update
Reset: Reset
PublishPost: Publish post
SaveDraft: Save draft
ChangeSaved: Changes Saved
UpdateSite: Update site

File: File
FileTooLarge maxSize@Int: The file is too large. The maximum file size is #{show maxSize} MB.
FileTypeNotAllowed: File type not allowed.
NoFileSelected: No file selected.
Link: Link
Description: Description
Uploaded: Uploaded
FileExists name@Text: The file named #{name} already exites!
FileSaved: File saved
SomethingWrong: Something went wrong
Action: Action
Copy: Copy
ClickToCopy: Click to copy
FileDeletionConfirmation: Are you sure that you want to delete the file?
FileDeleted: File Deleted.
NewFile: Upload new file
Okay: Okay
Cancel: Cancel
Continue: Continue
Sure: Yes, I'm sure
TheLastLoginMethod: This is your last login method, which can't be deleted.
LoginDeletionConfirmation: Are you sure to delete the login method? Then you can't login via it any more.
EmailDeletionConfirmation: Are you sure to delete the email? Then you can't login via it any more.
LoginDeleted: Login method deleted
EmailDeleted: Email deleted

InputFormat: Which format do you want to write you post in?
OutputFormat: Which format do you want to publish your post in?
Format: format
Post: Post
Posts: Posts
NewPost: New post
FirstPost: Write your first post. 
CommentsOn: Comments on
RecentEntries: Recent posts
RecentComments: Recent comments
RecentCommentsOn: Recent comments on
NoPost: No post found.
Tag: Keyword
Tags: Keywords
ViewAll: View all
Home: Home

NothingFound: Nothing Found
UnknownUser: Unknown user
Publish: Publish
HasSite: You have already registered a site

NoComment: No comment found. 
NewComment: Add a comment
Comment: Comment
Comments: Comments
CommentPublished: Comment published
LoginToComment: You must be logged in to comment
CommentDeleted: Comment deleted
Reply: Reply

AboutPageReset: Your about page has been reset.
PageDeleted: Page deleted
PageSaved: Page saved
PageNotFound: Page not found
Pages: Pages
NoPage: No page found.

Users: Members

InvalidAction: Invalid action
ComingSoon: Coming soon...
