PermissionDenied: Permission denied

SitePath: Site path
RegisterSite: Register a blog site
SiteRegistrationSucceed: Congratulations! You have successfully registered a new site. 
VisitHomepage: Click the following link to vist your site homepage: 
SiteRegistrationFailed: The site path has been registered by others. Please choose another path.
EnterPath: Enter your site path below. 
PathRegex: A path must begin with a lowercase letter and consists of lowercase letters, hyphens and digits.
FormMissing: Form data missing
FormFailure: Form data invalid

Account: Account
Unregister: Unregister
UnregistrationWarning: If you are really sure that you want to unregister your account, please enter the precise confirmation text below.
UserUnregistrationConfirmation: I understand that this action is irreversible and I will lose my posts, my comments, others' comments on my posts, and everything else associated with my account.
UnregistrationSuccess: Your account has been unregistered. 
UnregistrationFailure: Account unregistration failed.
PleaseConfirmUnregistration: Please enter the precise confirmation text to delete your account.
ID: ID. 
Password: Password
ForgotPassword: Forgot password
SetPassword: Set a new password
EnterPasswordResetEmail: Enter your e-mail address below, and a password reset e-mail will be sent to you.
Or: or
Login: Login
LoginViaEmail: Login via email
SignInWithGoogle: Sign in with Google
NewGoogle: Connect to a new google account
Email: Email
Site: Site
Profile: Profile
User: User
Users: Members
ActiveUsers: Active members
UnregisteredUser: [Unregistered]
Anonymous: Anonymous
Name: Name
Avatar: Avatar
About: About
VerifyAndSave: Verify & save
VerificationNoRelMeLink: Verification failed. Please ensure that you have pasted the verification link into your about page.
VerificationNoResponse: Verification failed. Please ensure that your about page is accessible.
Subscription: Subscription
Notification: Notification
EmailNotification: Email notification
NotifyMeViaEmail: Notify me via email when I receive a comment or reply.
NewEmail: Add a new email
Editor: Editor
DefaultFormat: Default Post Format
DefaultPreamble: Default LaTeX Preamble
Preamble: LaTeX Preamble
DefaultCitation: Default Citation
Citation: Citation
Edit: Edit
View: View
Save: Save
Update: Update
Reset: Reset
PublishPost: Publish post
SaveDraft: Save draft
ChangeSaved: Changes Saved
UpdateSite: Update site

File: File
FileTooLarge maxSize@Int: The file is too large. The maximum file size is #{show maxSize} MB.
FileTypeNotAllowed: File type not allowed.
NoFileSelected: No file selected.
Link: Link
Description: Description
Uploaded: Uploaded
FileExists name@Text: The file named #{name} already exites!
FileSaved: File saved
SomethingWrong: Something went wrong
Action: Action
Copy: Copy
ClickToCopy: Click to copy
FileDeletionConfirmation: Are you sure that you want to delete the file?
FileDeleted: File Deleted.
NewFile: Upload new file
Okay: Okay
Cancel: Cancel
Continue: Continue
Sure: Yes, I'm sure
TheLastLoginMethod: This is your last login method, which can't be deleted.
LoginDeletionConfirmation: Are you sure to delete the login method? Then you can't login via it any more.
EmailDeletionConfirmation: Are you sure to delete the email? Then you can't login via it any more.
LoginDeleted: Login method deleted
EmailDeleted: Email deleted

InputFormat: Which format do you want to write you post in?
OutputFormat: Which format do you want to publish your post in?
Format: format
Post: Post
Posts: Posts
LatestPosts: Latest posts
NewPost: New post
FirstPost: Write your first post. 
CommentsOn: Comments on
RecentEntries: Recent posts
RecentComments: Recent comments
RecentCommentsOn: Recent comments on
NoPost: No post found.
Tag: Keyword
Tags: Keywords
ViewAll: View all
Home: Home

NothingFound: Nothing Found
Publish: Publish
HasSite: You have already registered a site

NoComment: No comment found. 
NewComment: Add a comment
Comment: Comment
Comments: Comments
CommentPublished: Comment published
CommentDeleted: Comment deleted
Reply: Reply

AboutPageReset: Your about page has been reset.
PageDeleted: Page deleted
PageSaved: Page saved
PageNotFound: Page not found
Pages: Pages
NoPage: No page found.

InvalidAction: Invalid action
ComingSoon: Coming soon...

Subscribe: Subscribe
AlreadySubscribed email@Text: You have already subscribed via email #{email}.
SubscriptionConfirmationSent email@Text: A confirmation email has been sent to #{email}. Please click the link in the email to confirm your subscription.
UserSubscriptionConfirmation email@Text: Your subscription via email #{email} has been confirmed. You will receive an email notification when the author publishes a new post.
EntrySubscriptionConfirmation email@Text: Your subscription via email #{email} has been confirmed. You will receive an email notification when the post receives a new comment.
Unsubscribe: Unsubscribe
UnsubscribeAll: Unsubscribe all
SubscribeToUser: Please enter your email address below. You will receive an email notification when the author publishes a new post.
SubscribeToEntry: Please enter your email address below. You will receive an email notification when the post receives a new comment.
UserSubscriptionsDescription: You are subscribed to the following members. You will receive an email notification when they publish a new post.
PostSubscriptionsDescription: You are subscribed to the following posts. You will receive an email notification when they receive a new comment.
NoSubscription: No subscription found.
EmailSubscriptions: Email subscriptions
EmailAddress: Email address
SubscriptionVerified: Your subscription has been verified.
SubscriptionDeleted: Subscription deleted
VerificationEmailSent email@Text: A verification email has been sent to #{email}. Please click the link in the email to verify your account.

Feedback: Feedback
FeedbackSentDescription: Your feedback has been sent. Thank you!
Send: Send
SendAFeedback: Send a feedback

Search: Search
SearchReultsFor query@Text: Search results for "#{query}"
PostsContaining query@Text: Posts containing "#{query}"